anime_seek/anime/urls.py
from typing import ValuesView
from django.urls import path
from . import views
# (. significa que importa views da mesma directoria)
app_name = 'anime'
urlpatterns = [
        # anime
        path("", views.anime, name="anime"),
        # anime/3/home
        path("<int:user>/home", views.home, name="home"),
        #anime/login
        path("login", views.loginview, name="loginview"),
        #anime/register
        path("register", views.register, name="register"),
        #anime/add_anime
        path("<int:user>/add_anime", views.add_anime,name="add_anime"),
        #anime/definir_generos
        path("<int:user>/definir_generos", views.definir_generos,name="definir_generos"),
        #anime/3/admin
        path("<int:user>/admin",views.admin,name="admin"),
        #anime/logout
        path("logout", views.logoutview, name="logoutview"),
        #anime/3/personalizar
        path("<int:ide>/personalizar", views.personalizar,name="personalizar"),
        #anime/3/alterar_username
        path("<int:user>/alterar_username", views.alterar_username,name="alterar_username"),
        #anime/3/data
        path("<int:user>/data", views.data,name="data"),
        #anime/3/utilizadores
        path("<int:user>/utilizadores", views.utilizadores,name="utilizadores"),
        #anime/1/3/detail
        path("<int:a>/<int:u>/detail",views.detail,name="detail"),
        #anime/3/4/user
        path("<int:user>/<int:following>/user",views.user,name="user"),
        #anime/3/4/add_user
        path("<int:user>/<int:following>/add_user",views.add_user,name="add_user"),
        #anime/3/4/delete_user_from_list
        path("<int:user>/<int:following>/delete_user_from_list",views.delete_user_from_list,name="delete_user_from_list"),
        #anime/3/4/admin_delete_user
        path("<int:user>/<int:delete>/admin_delete_user",views.admin_delete_user,name="admin_delete_user"),
        #anime/1/3/admin_delete_anime
        path("<int:anime>/<int:user>/admin_delete_anime", views.admin_delete_anime,name="admin_delete_anime"),
        #anime/1/3/delete_anime_from_list
        path("<int:anime>/<int:user>/delete_anime_from_list",views.delete_anime_from_list,name="delete_anime_from_list"),
        #anime/3/import_data
        path("<int:user>/import_data",views.import_data,name="import_data"),
        #anime/3/my_list
        path("<int:user>/my_list",views.my_list,name="my_list"),
        #anime/3/amigos
        path("<int:user>/amigos",views.amigos,name="amigos"),
        #anime/1/3/add_to_list
        path("<int:anime>/<int:user>/add_to_list",views.add_to_list,name="add_to_list"),
        #anime/1/3/todas_reviews
        path("<int:a>/<int:u>/todas_reviews",views.todas_reviews,name="todas_reviews"),
        #anime/3/1/create_reviews
        path("<int:user>/<int:anime>/create_review",views.create_review,name="create_review"),
        #anime/3/erro_imagem
        path("<int:ide>/erro_imagem", views.personalizar, name="erro_imagem"),
        #anime/3/create_otaku_admin
        path("<int:user>/create_otaku_admin",views.create_otaku_admin,name="create_otaku_admin"),


]

anime_seek/anime_seek/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [path('anime/', include('anime.urls')),path('admin/', admin.site.urls),]
if settings.DEBUG:
         urlpatterns += static(settings.MEDIA_URL,
                     document_root=settings.MEDIA_ROOT)

anime_seek/anime/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import datetime


class Otaku(models.Model): 
    """
    Características de um utilizador
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    birthdate = models.DateField()
    path_image= models.CharField(max_length=30)
    
class Generos(models.Model):
    """
    Géneros do anime
    """ 
    genero = models.CharField(max_length=30,default=None) 

    def __str__(self):
        return self.genero
    
class Anime(models.Model):
    """
    Características do anime
    """
    anime = models.CharField(max_length=50)
    episodios= models.PositiveIntegerField() 
    generos = models.ForeignKey(Generos,on_delete=models.CASCADE,default=None)
    logo = models.CharField(max_length=500,default=None)

    def __str__(self):
        return self.anime

class List(models.Model): 
    """
    Lista de animes visto pelo utilizador, default ainda não viu
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    anime = models.ForeignKey(Anime, on_delete=models.CASCADE)
    watch = models.BooleanField(default=False)


class Review(models.Model):
    """
    Review feita pelo utilizador ao anime
    """
    anime = models.ForeignKey(Anime,on_delete=models.CASCADE) 
    user= models.ForeignKey(User, on_delete=models.CASCADE) 
    comentario = models.CharField(max_length=200)
    pub_data = models.DateTimeField('data de publicacao')

    def __str__(self):
        return self.comentario

    def foi_publicada_recentemente(self):
        return self.pub_data >= timezone.now() - datetime.timedelta(days=1)

class Friends(models.Model): 
    """
    Seguir um utilizador
    """
    following = models.ForeignKey(User,related_name ="following",default=None,on_delete=models.CASCADE)
    user = models.ForeignKey(User,related_name ="user",on_delete=models.CASCADE,default=None)

anime_seek/anime/views.py
from django.shortcuts import get_object_or_404,render,redirect
from django.http import HttpResponseRedirect,HttpResponseForbidden
from .models import Otaku,Generos,Anime,Friends,Review,List
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.files.storage import FileSystemStorage
from pathlib import Path
import os
import csv
from django.db.models import Count

# Create your views here.
def anime(request):
    """
    View que abre a página inicial da página web,
    Contém o login e a possibilidade de registar 
    um utilizador
    """
    return render(request, 'anime/anime.html')

@login_required
def home(request,user):
    """
    View que corresponde à página inicial do utilizador:
    Mostra o utilizador, a sua imagem de perfil 
    e ainda o número de utilizadores e animes adicionados 
    à lista do utilizador.
    Adicionalmente, mostra o top 3 de animes adicionados à lista do utilizadores
    """
    u = User.objects.get(id=user)
    try:        
        otaku = Otaku.objects.get(user=u)
    except Otaku.DoesNotExist:
        return HttpResponseRedirect(reverse("anime:create_otaku_admin",args=(user,)))
    friends = Friends.objects.filter(user=user).count()
    lista = List.objects.filter(user=user).count()
    # get top 3 animes in list
    a=List.objects.values("anime").annotate(c=Count('anime_id')).order_by('-c')[:3]
    contador=0
    animes=[]
    for course in a:
        an=course['anime']
        anime=Anime.objects.get(id=an)
        animes.append(anime)
        contador +=1
        if contador==3:
            return render(request, 'anime/home.html',{'user':user,"otaku":otaku,"friends":friends,"animes":lista,'top':animes})
    return render(request, 'anime/home.html',{'user':user,"otaku":otaku,"friends":friends,"animes":lista})

def create_otaku_admin(request,user):
    """
    View que permite que o admin que se registe como otaku, 
    com o intuito de o mesmo ter uma imagem default 
    """
    if request.method == 'POST':
        try:
            birthdate = request.POST.get('birth')
        except KeyError:
            return render(request,"anime/admin_register.html",{"user":user})
        if birthdate:
            u = User.objects.get(id=user)
            ut = Otaku(user=u, birthdate=birthdate,path_image="")
            ut.save()
            print("salvou")
            print(user)
            return HttpResponseRedirect(reverse("anime:home",args=(user,)))
        else:
            return HttpResponseRedirect(reverse("anime:create_otaku_admin",args=(user,)))
    else:
        return render(request, 'anime/admin_register.html',{"user":user})

@login_required
def admin(request,user):
    """
    View que abre o template admin que permite fazer adições à 
    base de dados
    """
    return render(request, 'anime/admin.html',{'user':user})

@login_required
def data(request,user):
    """
    View que abre o template data_base com o intuito de 
    mostrar todos animes registados na base de dados
    """
    anime = Anime.objects.all()
    return render(request,'anime/data_base.html',{'anime': anime, 'user':user})

@login_required
def detail (request,a,u):
    """
    View que abre o template detail com o intuito de mostrar em
    detalhe o anime selecionado pelo utilizador 
    """
    user=User.objects.get(id=u)
    anime = Anime.objects.get(id=a)
    context={"a":anime,"loop":range(0,anime.episodios),"user":user} # loop serve para mostrar os episódios do anime correspondente
    return render (request,"anime/detail.html",context=context)

@login_required
def todas_reviews(request,a,u):
    """
    View que abre o template reviews com o intuito de mostrar 
    todas as reviews feitas ao anime em questão
    """
    anime = Anime.objects.get(id=a)
    review = Review.objects.filter(anime=anime.id).all
    context={"review":review,"user":u,"anime":anime}
    return render (request,"anime/reviews.html",context=context)

@login_required
def my_list(request,user):
    """
    View que abre o template my_list com o intuito de mostrar
    todos os animes adicionados pelo utilizador
    """
    user = User.objects.get(id=user)
    listing = List.objects.filter(user=user.id).all
    context={"list":listing,"user":user}
    return render (request,"anime/my_list.html",context)

def utilizadores(request,user):
    """
    View que abre o template utilizadores com o intuitos de mostrar
    todos os utilizadores registados na base de dados
    """
    utilizadores = User.objects.all()
    return render(request,'anime/utilizadores.html',{'utilizadores': utilizadores, 'user':user})
    
def amigos(request,user):
    """
    View que abre o template amigos com o intuito de mostrar
    todos os utilizadores que o utilizador segue 
    """
    user = User.objects.get(id=user)
    listing = Friends.objects.filter(user=user.id).all
    context={"list":listing,"user":user}
    return render (request,"anime/amigos.html",context)

@login_required
def user(request,user,following):
    """
    View que abre o template user com o intuito de mostrar em 
    detalhe o perfil do utilizador que o user principal vai seguir ou
    deixar de seguir
    """
    user=User.objects.get(id=user)
    following=User.objects.get(id=following)
    o = Otaku.objects.get(id=following.id) 
    friends = Friends.objects.filter(user=following.id).count()
    lista = List.objects.filter(user=following.id).count()
    context={"user":user,"following":following, "image":o.path_image,"friends":friends,"animes":lista,}
    return render (request,"anime/user.html",context=context)

@login_required
def add_user(request,user,following):
    """
    View que permite ao utilizador seguir outro.
    Não é permitido o utilizador seguir-se a si mesmo, pois 
    é redirecionado a uma página de erro
    """
    if request.method == 'POST':
        u = User.objects.get(id=user)
        f = User.objects.get(id=following) 
        if u.id==f.id:
            context = {"add_me":u}
            return render(request, 'anime/error.html',context)
        w,created = Friends.objects.get_or_create(user=u,following=f)
        w.save()
        print('saved')
        return HttpResponseRedirect(reverse("anime:amigos",args=(user,)))
    return render(request, 'anime/user.html',{'user':following})


def loginview(request):
    """
    View que permite fazer o login, redirecionando para a página Home. 
    Por default a imagem é anime/static/anime/images/default.jpg. 
    Caso o utilizador introduza um username ou password errada 
    é direcionado a uma página de erro
    """
    if request.method =='POST':
        try:
            username = request.POST['user']
            password = request.POST['password']
            user = authenticate(username=username,password=password)
        except KeyError:
            return render(request,"anime/anime.html")
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('anime:home',args=(user.id,)))
        else:
            return HttpResponseForbidden('wrong username or password') 
    return render(request,'anime/anime.html',{"user":user})

@login_required
def logoutview(request):
    """ View que permite realizar o logout do utilizador """
    logout(request)
    return HttpResponseRedirect(reverse('anime:anime'))

def register(request):
    """ View que permite fazer o registo de um utilizador.
    Após o registo é direcionado para a página de login."""
    if request.method == 'POST':
        try:
            email = request.POST.get('e-mail')
            username = request.POST.get('username')
            password = request.POST.get('password')
            birthdate = request.POST.get('birthdate')
        except KeyError:
            return render(request,"anime/register.html")
        if email and username and password and birthdate:
            user = User.objects.create_user(email=email, username=username, password=password)
            ident = user.id
            ut = Otaku(user=user, birthdate=birthdate,path_image="")
            ut.save()
            print(' gravou')
            return HttpResponseRedirect(reverse("anime:anime"))
        else:
            return HttpResponseRedirect(reverse("anime:register"))
    else:
        return render(request, 'anime/register.html')

def personalizar(request, ide):
    """ 
    View que permite ao utilizador mudar a sua imagem de perfil, 
    eliminado a antiga
    """
    if request.method == 'POST':
        try:
            myfile = request.FILES['myfile']
        except KeyError:
            return render(request,'anime/personalizar.html', {'ide':ide})
        if myfile:
            fs = FileSystemStorage()
            u = User.objects.get(pk=ide)
            o = Otaku.objects.get(user=u.id)
            name = str(ide)
            file = name + '.jpg'
            teste = Path("anime/static/media/" + file)
            print('cewbic'+ str(myfile))
            if os.path.exists(teste): 
                old_path = 'anime/static/media/'
                os.remove(old_path + file)
                filename = fs.save(file, myfile)
                uploaded_file_url = fs.url(filename)
            else:
                old_path = 'anime/static/media/'
                filename = fs.save(file, myfile)
                uploaded_file_url = fs.url(filename)
            o.path_image = filename
            o.save()       
        return HttpResponseRedirect(reverse('anime:home', args=(ide,)) )
    return render(request, 'anime/personalizar.html', {'ide':ide})

@login_required
def definir_generos(request,user):
    """
    View que permite ao admin adicionar manualmente novos 
    géneros à base de dados
    """
    if request.method == 'POST':
        try:
            genero = request.POST.get('genero')
        except KeyError:

anime_seek/anime/templates/anime/admin.html
{% load static %}
<head>
  <link rel="stylesheet" href="{% static 'anime/style.css' %}" />
  <title> Admin </title>
</head>
<style>

</style>
<body>
{%if request.user.is_superuser%}
    <img src="{% static "anime/images/Logo_anime_seek.png" %}" width="120px" height="80px" align="left">
                <br>
                <br>
                <br>
                <br>
                <br>
                <div class="top_nav">
                    <ul>
                    <li><a href="{% url "anime:home" user %}">Home</a></li>
                    <li><a href="{% url "anime:data" user %}">Animes</a></li>
                    <li><a href="{% url "anime:utilizadores" user%}">Otakus</a></li>
                    <li><a href="{% url "anime:amigos" user %}">A seguir</a></li>
                    <li><a href="{% url "anime:my_list" user %}">A minha lista</a></li>
                    <div class="top_nav_right">
                        <li><a href="{% url "anime:logoutview" %}">Logout</a></li>
                    </div>
                    </ul>
                </div>
        <h1 align="center"> Adições à base de dados: </h1>
        <div class="row">
            <div class="column1">
                <p> Adicionar Anime Manualmente: </p>
                <form name="add_anime" action="{% url 'anime:add_anime' user %}" method="post">
                    {% csrf_token %}
                    <p>Nome Anime:</p><input type="text" name="nome">
                    <p>Nº episódios totais:</p><input type="number" name="episodios">
                    <p>Géneros:<p><input type="text" name="genero">
                    <p>Imagem:<p><input type="url" name="logo">
                    <br>
                    <br>
                    <input type="submit" value="Registar">
                </form>
            </div>
            <div class="column2">
                <p> Adicionar Géneros: </p>
                <form name="definir_generos" action="{% url 'anime:definir_generos' user %}" method="post">
                    {% csrf_token %}
                        <p>Género:</p><input type="text" name="genero">
                        <br>
                        <input type="submit" value="Registar">
                </form>
            </div>
            <div class="column3">
                <p> Importar dados da base de dados <strong>csv</strong></p>
                <center>
                <h5>Estrutura da base de dados:</h5>
                <ul>
                        <li>Coluna de título denomina-se por <strong>title</strong></li>
                        <li>Coluna do género denomina-se por <strong>genre</strong></li>
                        <li>Coluna de nº de episodios denomina-se por <strong>episodes</strong></li>
                        <li>Coluna com link para imagem de anime denomina-se por <strong>img_ur</strong></li>
                </ul>
                <center>
                <form name="import_csv" action="{% url 'anime:import_data' user%}" method="post">
                    {% csrf_token %}
                    <p>Ficheiro:</p><input type="text" name="file">
                        <br>
                        <input type="submit" value = "Submeter">
                </form>        
            </div>
        </div>

{%endif%}
</body>

anime_seek/anime/templates/anime/amigos.html
{% load static %}
<head>
  <link rel="stylesheet" href="{% static 'anime/style.css' %}" />
  <title> User List </title>
</head>
<style>

</style>
<body>
            <img src="{% static 'anime/images/Logo_anime_seek.png' %}" width="120px" height="80px" align="left">
            <br>
            <br>
            <br>
            <br>
            <br>
        <div class="top_nav">
            <ul>
            <li><a href="{% url 'anime:home' user.id %}"> Home </a></li>
            <li><a href="{% url 'anime:data' user.id %}">Animes</a></li>
            <li><a  href="{% url 'anime:utilizadores' user.id %}">Otakus</a></li>
            <li><a class="active" href="{% url 'anime:amigos' user.id %}">A seguir</a></li>
            <li><a href="{% url 'anime:my_list' user.id %}">A minha lista</a></li>
            <div class="top_nav_right">
                <li><a href="{% url 'anime:logoutview' %}">  Logout  </a></li>
            </div>
            </ul>
        </div>
        <br>
        {%if list%}      
            {% for l in list %}             
                <div class="u">
                    <a href="{% url 'anime:user' user.id l.following.id %}">
                    <div class="con">                        
                        <div class="outline_image">
                            {% if l.following.otaku.path_image == "" %}
                                <img src="{% static 'anime/images/default.jpg' %}"  class="user_img">
                            {% else %}
                                <img src="/anime/static/media/{{l.following.id}}.jpg"  class="user_img">
                            {% endif %}
                        </div> 
                        
                        <div class="username_style">
                            <h3>
                            {{l.following.username}}
                            </h3>
                        </div>

                    </div>  
                    </a>
                </div>
            {%endfor%}
        {% else %}
            <p> Ainda não tens amigos adicionados. Para adicionar vai a <a href="{% url 'anime:utilizadores' user.id %}">Otakus</a>, clica no amigo e segue-o :) Diverte-te</p>
        {%endif%}
</body> 

anime_seek/anime/templates/anime/detail.html
{% load static %}
<head>
  <link rel="stylesheet" href="{% static 'anime/style.css' %}" />
  <title> Detail </title>
</head>
<style>

</style>
<body>
{% if request.user.is_authenticated %}
        <img src="{% static "anime/images/Logo_anime_seek.png" %}" width="120px" height="80px" align="left">
        <br>
        <br>
        <br>
        <br>
        <br>
    <div class="top_nav">
        <ul>
            <li><a href="{% url "anime:home" user.id %}"> Home </a></li>
            <li><a href="{% url "anime:data" user.id %}">Animes</a></li>
            <li><a href="{% url "anime:utilizadores" user.id %}">Otakus</a></li>
            <li><a href="{% url "anime:amigos" user.id %}">A seguir</a></li>
            <li><a href="{% url "anime:my_list" user.id %}">A minha lista</a></li>

            <div class="top_nav_right">
                <li><a class="active" href="{% url "anime:detail" a.id user.id %}">{{a.anime}}</a></li>
                <li><a href="{% url "anime:todas_reviews" a.id user.id %}">Reviews</a></li>
                <li><a href="{% url "anime:logoutview" %}">  Logout  </a></li>
            </div>
        </ul>
    </div>
    <br>
    <br>
    {% if a %}
    <div class="row">
        <div class="column1"> 
        <center>
        <div class="action">
            <ul>
                <li>
                    <form action="{% url "anime:add_to_list" a.id user.id %}" method='POST'>
                        {% csrf_token %}
                        <button type='submit'>Adicionar à minha lista de animes</button>
                    </form>
                </li>
                <li>
                    <form action="{% url "anime:delete_anime_from_list" a.id user.id %}" method='POST'>
                        {% csrf_token %}
                        <button type='submit'>Remover da minha lista de animes</button>
                    </form>
                </li>
                {%if request.user.is_superuser%}
                <li>
                    <form action="{% url "anime:admin_delete_anime" a.id user.id %}" method='POST'>
                        {% csrf_token %}
                        <button type='submit'>Remover anime da base de dados</button>
                    </form>
                </li>
                {%endif%}
            </ul>
        </div>
    </center>
        </div>
        <div class="column2">
            <div class="content">
                <h4>Título</h4>
                <h2> {{a.anime}} </h2>
                <h4>Géneros</h4>
                <p> {{a.generos}} </p>
                <h4>Episódios</h4>
                <div class="botao">
                    {% for e in loop %}
                    <button>{{e}}</button>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class='column3'>
            <img src="{{a.logo}}" width="70%px" height="70%">
            <div class="img_desc">
                <p>Imagem proveniente de <a href="https://myanimelist.net">Myanimelist</a></p>
            </div>
        </div>
    </div>
    {%endif%}
{%endif%}
</body>

anime_seek/anime/templates/anime/error.html
{% load static %}
<head>
  <link rel="stylesheet" href="{% static 'anime/style.css' %}" />
  <title> Error </title>
</head>
<style>

</style>  
<body>
  {% if request.user.is_authenticated %}
  <img src="{% static "anime/images/Logo_anime_seek.png" %}" width="120px" height="80px" align="left">
  <br>
  <br>
  <br>
  <br>
  <br>
<div class="top_nav">
  <ul>
    <li><a href="{% url "anime:home" user.id %}"> Home </a></li>
    <li><a href="{% url "anime:data" user.id %}">Animes</a></li>
    <li><a href="{% url "anime:utilizadores" user.id %}">Otakus</a></li>
    <li><a href="{% url "anime:amigos" user.id %}">A seguir</a></li>
    <li><a href="{% url "anime:my_list" user.id %}">A minha lista</a></li>
    <div class="top_nav_right">
      <li><a href="{% url "anime:logoutview" %}">  Logout  </a></li>
    </div>
  </ul>
</div>
  {%if add_me%}
    <p> Não te podes seguir a ti mesmo ;) </p>
    
  {%endif%}
  {% if not_add_anime%}
    <p> O anime que pretendes remover não se encontra na tua lista </p>
  {%endif%}
  {%if not_add_user%}
  <p> Não segues este utilizador</p>
  {%endif%}
  {%endif%}
</body>

anime_seek/anime/templates/anime/home.html
{% load static %}
<head>
  <link rel="stylesheet" href="{% static 'anime/style.css' %}" />
  <title> HOME </title>
</head>
<style>

</style>
<body>
  {% if request.user.is_authenticated %}
      <img src="{% static "anime/images/Logo_anime_seek.png" %}" width="120px" height="80px" align="left">
      <br>
      <br>
      <br>
      <br>
      <br>
    <div class="top_nav">
      <ul>
        <li><a class="active" href="{% url "anime:home" user %}"> Home </a></li>
        <li><a href="{% url "anime:data" user %}">Animes</a></li>
        <li><a href="{% url "anime:utilizadores" user %}">Otakus</a></li>
        <li><a href="{% url "anime:amigos" user %}">A seguir</a></li>
        <li><a href="{% url "anime:my_list" user %}">A minha lista</a></li>
        <div class="top_nav_right">
          <li><a href="{% url "anime:logoutview" %}">  Logout  </a></li>
        </div>
      </ul>
    </div>
      <div style="width: 1O0%;">
        <div class = 'Home_l' style="width: 50%; height: 100%; float: left;"> 
            <h2>Olá {{ request.user.username }} ! </h2> 
            <div class="center">
              {% if otaku.path_image == "" %}
                <img src="{% static 'anime/images/default.jpg' %}" alt ="Profile Image" width='140' height="140">
              {% else %}
                <img src="/anime/static/media/{{request.user.id}}.jpg" alt ="Profile Image" width='140' height="140">
              {% endif %}
                <br>  
                  <a href="{% url 'anime:personalizar' user %}"> Alterar imagem </a>
                <br>
              <div class="box_names">
                <h5>Username</h5> 
                  <p>{{ request.user.username }}</p>
                  <a href="{% url 'anime:alterar_username' user %}"> Alterar username </a>
                <h5>Email</h5>
                  <p>{{ request.user.email }}</p>
                <h5>Último login</h5> 
                  <p>{{ request.user.last_login}}</p>
                <h5>A seguir</h5>
                  <div class="number">
                    <h3>{{friends}}</h3>
                  </div>
                <h5>Animes</h5>
                <div class="number">
                  <h3>{{animes}}</h3>
                </div>
              </div>
          </div> 
        </div>
        <div class='Home_r' style="margin-left: 50%; height: 100%;"> 
          <br>
          {%if request.user.is_superuser%}
            <div class="button">
              <h4> Fazer alterações à base de Dados: </h4>
              <a href="{% url "anime:admin" user%}"> <button> + </button> </a>
            </div>
          {%endif%}

          <br>
          <br>
          <div class="top">
              <table>
                <tr>
                  <th colspan="2"><h3>Top 3 Animes</h3></th>
                  </tr>
                <tr>
                  <td>
                    <h4>Imagem</h4>
                  </td>
                  <td>
                    <h4>Anime</h4>
                  </td>
                </tr>
                {%for i in top%}
                <tr>
                  <td> 
                    <a href="{% url 'anime:detail' i.id user%}">
                      <img src="{{i.logo}}" alt="logo" width='140' height="140">
                    </a>
                  </td>
                  <td>
                    <h3>{{i.anime}}</h3> 
                    <p>{{i.generos}}</p>
                  </td>
                </tr>
                {%endfor%}
              </table>
          </div>
        </div>

{%endif%}
</body>

anime_seek/anime/templates/anime/reviews.html
{% load static %}
<head>
  <link rel="stylesheet" href="{% static 'anime/style.css' %}" />
  <title> Detail </title>
</head>
<style>

</style>
<body>
{% if request.user.is_authenticated %}
    <img src="{% static "anime/images/Logo_anime_seek.png" %}" width="120px" height="80px" align="left">
    <br>
    <br>
    <br>
    <br>
    <br>
    <div class="top_nav">
        <ul>
            <li><a href="{% url "anime:home" user %}"> Home </a></li>
            <li><a href="{% url "anime:data" user %}">Animes</a></li>
            <li><a href="{% url "anime:utilizadores" user %}">Otakus</a></li>
            <li><a href="{% url "anime:amigos" user %}">A seguir</a></li>
            <li><a href="{% url "anime:my_list" user %}">A minha lista</a></li>
        <div class="top_nav_right">
            <li><a href="{% url "anime:detail" anime.id user %}">{{anime.anime}}</a></li>
            <li><a class="active" href="{% url "anime:todas_reviews" anime.id user %}">Reviews</a></li>
            <li><a href="{% url "anime:logoutview" %}">  Logout  </a></li>
        </ul>
    </div>
    <div class="leftpane">   
        <div class="leftpane_upper"> 
            <h3> {{anime}} </h3>
            <h4> {{a.generos}} </h4>
                <img src="{{anime.logo}}" width='250px' >

                <h3> Adicionar Review</h3>
                <form name="user" action="{% url 'anime:create_review' user anime.id%}" method="post">
                    {% csrf_token %}
                        <input type="text" name="review">
                        <br>
                        <input type="submit" value = "Submit">
                </form>        
        </div>
    </div>

    <div class="rightpane">
        {% if review%}
        {% for r in review %}   
            <div class="u2">
                <div class="con2">    
                        <div class="outline_image">
                            {% if r.user.otaku.path_image == "" %}
                                <img src="{% static '/anime/images/default.jpg' %}" class="user_img">
                            {% else %}
                                <img src ="/anime/static/media/{{r.user.id}}.jpg" class="user_img">
                            {% endif %} 
                        </div>

                        <div class="texto">
                            <div class="username_style2">

                                <span>   
                                    <strong>{{r.user.username}}</strong> <small>{{r.pub_data}}</small>
                                </span> 
                                <p>{{r.comentario}}</p>  
                            </div>       

                        </div>
                </div>  
            </div>
        {%endfor%}
        {%else%}
            <p> Ainda não existem reviews feitas a este anime. Sê o primeiro :)</p>
        {%endif%}
    </div>

{%endif%}
</body>